# -*- coding: utf-8 -*-
"""app.py (Trader_Sentiment_Analysis: Streamlit Dashboard).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gllWjTIN6Xk5q0Wp7ZATCyeMLdkptE9
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Trader Sentiment Dashboard", layout="wide")

st.title("📊 Trader Performance vs Market Sentiment")

# Sidebar
st.sidebar.header("Upload Data")
sentiment_file = st.sidebar.file_uploader("Sentiment CSV", type=["csv"])
trades_file = st.sidebar.file_uploader("Trades CSV", type=["csv"])

if sentiment_file and trades_file:

    # Load data
    sentiment = pd.read_csv(sentiment_file)
    trades = pd.read_csv(trades_file)
    # Clean column names
    sentiment.columns = sentiment.columns.str.lower()
    trades.columns = trades.columns.str.lower()

    # Convert dates
    sentiment['date'] = pd.to_datetime(sentiment['date'])
    trades['timestamp'] = pd.to_datetime(trades['timestamp'], unit='ms')

    sentiment['date'] = sentiment['date'].dt.date
    trades['date'] = trades['timestamp'].dt.date

    # Merge
    df = pd.merge(trades, sentiment[['date', 'classification']], on='date', how='left')

    # Feature engineering
    df['sentiment'] = df['classification'].apply(
        lambda x: 'Fear' if 'Fear' in str(x) else 'Greed'
    )
    df['is_long'] = df['side'].apply(lambda x: 1 if x == 'BUY' else 0)

    # ---------------- FILTER ----------------
    st.sidebar.subheader("Filters")
    sentiment_filter = st.sidebar.multiselect(
        "Select Sentiment", ['Fear', 'Greed'], default=['Fear', 'Greed']
    )

    df = df[df['sentiment'].isin(sentiment_filter)]
     # ---------------- TABS ----------------
    tab1, tab2, tab3, tab4 = st.tabs([
        "📌 Overview",
        "📊 PnL Analysis",
        "📈 Behavior",
        "🧩 Segmentation"
    ])

    # -------- TAB 1 --------
    with tab1:
        st.subheader("Dataset Overview")
        col1, col2 = st.columns(2)
        col1.metric("Total Trades", len(df))
        col2.metric("Unique Traders", df['account'].nunique())

        st.dataframe(df.head())

        # Sentiment distribution
        fig, ax = plt.subplots()
        df['sentiment'].value_counts().plot(kind='bar', ax=ax)
        ax.set_title("Sentiment Distribution")
        st.pyplot(fig)

    # -------- TAB 2 --------
    with tab2:
        st.subheader("PnL Distribution")

        fig, ax = plt.subplots()
        sns.boxplot(x='sentiment', y='closed pnl', data=df, ax=ax)
        st.pyplot(fig)

    # -------- TAB 3 --------
    with tab3:
        st.subheader("Trader Behavior")

        behavior = df.groupby('sentiment')[['size usd', 'is_long']].mean()

        fig, ax = plt.subplots()
        behavior.plot(kind='bar', ax=ax)
        st.pyplot(fig)

        st.write("Average Behavior Metrics:")
        st.dataframe(behavior)

    # -------- TAB 4 --------
    with tab4:
        st.subheader("Trader Segmentation")

        daily = df.groupby(['account', 'date']).agg(
            pnl=('closed pnl', 'sum'),
            trades=('account', 'count')
        ).reset_index()

        median_trades = daily['trades'].median()

        daily['type'] = daily['trades'].apply(
            lambda x: 'Frequent' if x > median_trades else 'Infrequent'
        )

        seg = daily.groupby('type')['pnl'].mean()

        fig, ax = plt.subplots()
        seg.plot(kind='bar', ax=ax)
        st.pyplot(fig)

    # -------- INSIGHTS --------
    st.markdown("---")
    st.subheader("🧠 Key Insights")

    st.markdown("""
    - Traders show higher activity during **Greed phases**
    - Increased activity does not ensure higher profits → possible overtrading
    - Fear phases indicate more cautious and stable trading behavior
    """)

else:
    st.info("👈 Upload both CSV files from the sidebar to begin")